---
name: XML-Atom-SimpleFeed
version: 0.8_001
author:
  - Aristotle Pagaltzis <pagaltzis@gmx.de>
abstract: No-fuss generation of Atom syndication feeds
license: perl
recommends:
  XML::SAX::Writer: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  XML::Atom::SimpleFeed:
    file: lib/XML/Atom/SimpleFeed.pm
    version: 0.8_001
generated_by: Module::Build version 0.2611
