---
name: XML-Atom-SimpleFeed
version: 0.83
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
abstract: No-fuss generation of Atom syndication feeds
license: perl
resources:
  license: ~
requires:
  perl: 5.8.1
build_requires:
  Test::More: 0
provides:
  XML::Atom::SimpleFeed:
    file: lib/XML/Atom/SimpleFeed.pm
    version: 0.83
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
