--- #YAML:1.0
name: XML-Atom-SimpleFeed
version: 0.8
author:
  - Aristotle Pagaltzis <pagaltzis@gmx.de>
abstract: No-fuss generation of Atom syndication feeds
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
