---
name: XML-Atom-SimpleFeed
version: 0.85
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
abstract: No-fuss generation of Atom syndication feeds
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.8.1
build_requires:
  Test::More: 0
provides:
  XML::Atom::SimpleFeed:
    file: lib/XML/Atom/SimpleFeed.pm
    version: 0.85
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
